Central-MakeUs/PeerNa-Web

vite.config.ts

<br>
<br><br>
<br><br>
<br><br>
- Close #
<br><br>

fix: vite 절대 경로 설정 변경

---

.storybook/preview.tsx
components.json
package.json
src/components/common/molecule/BottomNavigation.tsx
src/components/common/molecule/BottomSheet.tsx
src/components/ui/drawer.tsx
src/constants/styles.ts
src/index.css
src/main.tsx
src/store/bottomSheet.ts
src/stories/molecule/BottomSheet.stories.tsx
src/utils/shadcn.ts
tailwind.config.js
tsconfig.json
vite.config.ts
yarn.lock

<br>
shadcn-ui를 사용하여 BottomSheet을 구현했습니다.
<br><br>
- shadcn-ui 설치 및 설정
- shadcn을 사용해 Drawer component 생성
- 전역으로 BottomSheet을 사용하기 위해 recoil 설치
- BottomSheet 컴포넌트 구현 
<br><br>
- recoil 설치했습니다.
<br><br>
- Close #9 
<br><br>

feat: shadcn-ui 적용 및 BottomSheet  구현 #9

---

src/components/common/molecule/ProgressBar.tsx

<br>
- ProgressBar 스토리북 에러를 해결합니다
<br><br>
컴포넌트의 interface로 stepArray 타입을 삭제하고 에러를 해결합니다.
<br><br>

fix: ProgressBar 컴포넌트 스토리북 오류 해결

---

.gitignore
package.json
src/apis/common/index.ts
src/apis/index.ts
src/main.tsx
src/vite-env.d.ts
tsconfig.json
vite.config.ts
yarn.lock

<br>
api를 보내고 수신하는 것에 대해서 설정했습니다. 
<br><br>
- axios 설치
- axios instance 설정
- test api 작성 
- react-error-boundary 라이브러리 설치
- queryClient에 queries의 에러와 mutation의 에러를 분리하여 처리하게 설정했습니다. 
<br><br>
- /health에 get을 보내면 서버가 정상인지 확인할 수 있습니다.
- /ping에 post를 보내면 body에 담은 데이터가 반환됩니다.
api와 관련된 에러는 react-query의 queryClient에서 핸들링할 예정입니다.
javascript 로직과 관련된 부분은 ErrorBoundary 컴포넌트에서 핸들링할 예정입니다. 
참고자료는 협업 노션 페이지 기술 로그의 ErrorBoundary 컴포넌트, @tanstack/react-query 에러 핸들링 페이지에 적어두겠습니다. 
test를 위해서 https 설정을 했는데요. 
현재 서버에서 http 요청도 수락하기 때문에 따로 설정하실 필요는 없습니다. 
다만, 필요할 때 사용하려고 설치했기 때문에 만일 실행 중 에러가 발생한 경우에 말씀해주세요! 
<br><br>
- Close #17 
<br><br>

feat: api(axios) 기본 설정 및 에러 핸들링 기본 설정

---

src/components/common/atom/DatePicker.tsx
src/components/pages/peerReview/organism/InputProjectDate.tsx

<br>
DatePicker의 width값을 수정했습니다. 
<br><br>
컨테이너 크기에 맞게 자동으로 늘어날 수 있도록 고정된 width 값을 flex-1로 변경했습니다. 
<br><br>
<br><br>
- Close #37 
<br><br>

style: DatePicker width를 flex-1로 수정

---

src/components/pages/home/molecule/UserProfileList.tsx
src/components/pages/home/template/HomePage.tsx
src/components/pages/moreFeedback/template/MoreFeedbackPage.tsx
src/components/pages/peerType/template/PeerTypePage.tsx
src/components/pages/profileEdit/organism/ProfileEditList.tsx
src/hooks/api/useGetMoreFeedback.tsx
src/hooks/api/useGetSearchPeerPart.tsx
src/hooks/api/useGetSearchPeerType.tsx

<br>
- 동료페이지와 홈페이지의 query 타입들을 수정하였습니다.
- select 옵션을 사용하지않고 각 페이지에서 데이터를 mapping 하였습니다.
- 머지했을 때 다른 충돌사항이 있는지 확인부탁드립니다!
<br><br>
- Close #71 
<br><br>

fix: 홈페이지와 동료 페이지 쿼리 타입 전체 수정

---

src/pages/home/index/template/HomePage.tsx
vercel.json

<br>
테스트 도중에 온보딩으로 이동하는 현상을 수정했습니다. 
<br><br>
컴포넌트 외부에 있던 push 함수를 useEffect로 이동시켰습니다.
<br><br>
<br><br>
- Close #115 
<br><br>

fix: 테스트 도중 온보딩으로 이동하는 현상 수정 

---

src/pages/mypage/index/molecule/OverallOpinion.tsx

<br>
종합평가 하단의 마진값을 더 좁게 수정하였습니다.
<br><br>

style: 종합평가 마진값 수정

---

src/hooks/api/member/index/useGetMe.tsx

<br>
- 프로필 수정 시 getMe 쿼리 호출 안되는 문제 해결
- 모바일에서 버튼 줄바꿈 처리 no-wrap으로 해결
<br><br>

fix: 프로필 수정에서 api 호출 안되는 문제 해결

---

src/pages/notification/index/organism/ProjectNotificationTab.tsx
src/pages/notification/index/organism/ReviewNotificationTab.tsx
src/pages/notification/index/template/NotificationPage.tsx
src/pages/project/index/organism/MyProject.tsx
src/pages/project/index/organism/RecentProjectTab.tsx
src/pages/project/index/template/ProjectPage.tsx

<br>
알림탭에 페이지네이션을 적용했습니다.
<br><br>
<br><br>
<br><br>
- Close #131 
<br><br>

feat: Notification탭에 페이지네이션 적용

---

src/pages/mypage/setting/molecule/SettingMenu.tsx
src/pages/notification/index/organism/ProjectNotificationTab.tsx
src/pages/notification/index/organism/ReviewNotificationTab.tsx
src/pages/notification/index/template/NotificationPage.tsx
src/pages/project/index/organism/MyProject.tsx
src/pages/project/index/organism/RecentProjectTab.tsx
src/pages/project/index/template/ProjectPage.tsx
src/pages/review/index/molecule/ReviewHeader.tsx
src/pages/review/result/organism/ResultGuide.tsx

<br>
노션 링크를 반영했습니다. 
<br><br>
<br><br>
<br><br>
- Close #133 
<br><br>

feat: notion 약관 링크 반영

---

src/constants/images.ts
src/hooks/api/review/index/usePostUpdateMemberId.ts
src/pages/auth/redirect/template/RedirectPage.tsx
src/pages/developer/DeveloperPage.tsx
src/pages/review/index/template/ReviewPage.tsx
src/pages/review/result/organism/LoadingResult.tsx
src/pages/review/result/organism/ResultShare.tsx
src/utils/webview.ts

fix: LoadingResult 에러 수정 

---

src/components/common/molecule/ButtonContainer.tsx
src/components/common/molecule/Modals.tsx
src/components/common/molecule/ProfileListItem.tsx
src/components/common/molecule/WithdrawalModal.tsx
src/pages/home/index/template/HomePage.tsx
src/pages/mypage/index/molecule/SelfTestModal.tsx
src/pages/mypage/index/organism/CardContent.tsx
src/pages/mypage/index/organism/KeywordContent.tsx
src/pages/mypage/index/template/MyPage.tsx
src/pages/mypage/setting/molecule/SettingMenu.tsx
src/pages/mypage/setting/template/SettingPage.tsx
src/pages/peer/detail/atom/PeerProfileCard.tsx
src/pages/peer/detail/atom/PeerTestResult.tsx
src/pages/peer/detail/atom/SelfTestResult.tsx
src/pages/peer/detail/template/PeerDetailPage.tsx
src/pages/peer/type/template/PeerTypePage.tsx
src/store/modal.ts

<br>
- 프로필 이슈를 해결하였습니다.
<br><br>
- 셀프테스트 진행하지 않은 상태에서 마이페이지로 이동 시, 셀프테스트 모달이 뜨면서 셀프테스트로 이동하게끔 추가하였습니다.
<br><br>
- Close #152 
<br><br>

fix: 프로필 이슈 해결

---

package.json
src/hooks/common/useStackFlow.tsx
src/main.tsx
src/pages/auth/redirect/template/RedirectPage.tsx
src/pages/mypage/setting/template/SettingPage.tsx
src/pages/project/create/organism/ProjectForm.tsx
src/pages/review/result/organism/ResultShare.tsx
src/stories/common/molecule/RequestListItem.stories.tsx
tsconfig.json
yarn.lock

<br>
QA #157 의 작업을 수행했습니다. 
<br><br>
#157
<br><br>
- react-freeze를 써서 스택플로우에서 생기는 불필요한 렌더링을 방지했습니다. 
플러그인 코드 확인만 한 번 해주세요! 
<br><br>
- Close #157 
<br><br>

QA: 수정 사항 2차 반영 

---

src/constants/share.ts
src/hooks/api/member/index/usePostMemberWithdrawal.tsx
src/hooks/common/useSendKakoMessage.tsx
src/hooks/common/useShareLink.tsx
src/pages/home/index/atom/ReviewButton.tsx
src/pages/mypage/index/atom/PeerToolTip.tsx
src/pages/mypage/index/molecule/SelfTestModal.tsx
src/pages/mypage/index/template/MyPage.tsx
src/pages/project/projectId/template/ProjectDetailPage.tsx
src/pages/review/result/molecule/ShareDrawer.tsx

<br>
- qa 사항들을 반영하였습니다.
<br><br>
- 링크 공유와 카카오 공유를 useShareLink 훅을 작성하여 재사용하였습니다.
- 카카오 공유의 테스트 공유와 프로젝트 공유를 상수화하였습니다.
<br><br>
- Close #156 
- Close #158 
<br><br>

refactor: qa 반영

---

src/constants/activities.ts

<br>
- developerPage를 삭제합니다.
<br><br>

refactor: developerPage 삭제

---

src/components/common/molecule/Modals.tsx
src/components/common/molecule/ProjectJoinRequestModal.tsx
src/pages/project/projectId/template/ProjectDetailPage.tsx

<br>
프로젝트 제안 모달 버그를 수정했습니다. 
<br><br>
<br><br>
<br><br>
- Close #
<br><br>

프로젝트 제안 모달 버그 수정 

---

src/pages/mypage/moreProject/molecule/PeerProjectInfo.tsx
src/pages/mypage/moreProject/template/PeerProjectDetailPage.tsx
src/pages/peer/detail/template/PeerDetailPage.tsx
src/pages/peer/project/template/MyProjectListPage.tsx

<br>
- 프로젝트 리스트 수정
<br><br>
- 프로젝트 데이터의 mapping 중 옵셔널 체이닝을 추가합니다.
- 동료 상세 > 프로젝트 리스트의 링크 레이아웃을 수정합니다.
<br><br>

style: 프로젝트 리스트 수정

---

src/components/common/molecule/ProfileListItem.tsx
src/pages/mypage/index/atom/PeerToolTip.tsx
src/pages/mypage/index/atom/TotalScoreToolTip.tsx
src/pages/mypage/index/molecule/NoTestKeywordResult.tsx
src/pages/mypage/index/molecule/OverallTestResult.tsx
src/pages/peer/project/template/MyProjectListPage.tsx

<br>
- 추가적인 QA를 반영하였습니다.
<br><br>
- 프로필 리스트의 말줄임을 추가하였습니다. (1줄 이상)
- 폰트 크기는 늘렸지만 굵기는 기존의 굵기를 가져가도록 추가하였습니다.
- 툴팁의 위치를 top으로 설정하였습니다.
<br><br>

style: 레이아웃 수정

---

src/utils/image.ts

<br>
- 링크 공유 시, 잘못된 url을 수정하였습니다.
<br><br>
<br><br>

fix: 링크 공유 url 수정

---

src/components/common/atom/TextArea.tsx
src/components/common/molecule/AlreadyReviewModal.tsx
src/components/common/molecule/Modals.tsx
src/components/common/molecule/WithdrawalModal.tsx
src/hooks/api/member/index/usePostMemberWithdrawal.tsx
src/hooks/api/review/index/usePostPeerReviewReject.tsx
src/hooks/store/useReviewHistory.tsx
src/pages/notification/index/molecule/NotificationType.tsx
src/pages/notification/index/organism/ReviewNotificationTab.tsx
src/pages/review/index/template/ReviewPage.tsx
src/pages/review/peer/organism/InputProjectDate.tsx
src/pages/review/peer/organism/RequestInit.tsx
src/pages/review/self/template/ReviewSelfPage.tsx
src/store/modal.ts
src/store/reviewHistory.ts
src/type/index.ts

<br>
<br><br>
<br><br>
<br><br>
- Close #
<br><br>

feat: 탈퇴, 중복 리뷰 방지 

---

src/App.tsx
src/components/common/molecule/ProjectInviteModal.tsx
src/components/wrapper/Content.tsx
src/hooks/api/project/projectId/usePostPeerInviteProject.tsx
src/hooks/api/review/peerId/usePostRequestPeerTest.tsx
src/pages/mypage/moreProject/template/PeerProjectDetailPage.tsx
src/pages/review/peer/organism/WonderingMyCard.tsx
src/pages/review/peer/template/ReviewPeerPage.tsx
src/pages/review/result/molecule/Card.tsx
src/pages/review/result/organism/AnimationCards.tsx
src/pages/review/result/organism/ResultLoginRequired.tsx

- [] Assignees & Reviewers 
<br>
<br><br>
토스트 마진 추가
토스트 중복 이슈 수정
<br><br>
<br><br>
- Close #
<br><br>

QA 수정 사항 반영 

---

src/pages/home/index/organism/HomeBackground.tsx

<br>
- style 속성으로 background image css 작성하였습니다.
<br><br>

style: style 속성으로 background image css 작성

---

index.html
src/components/common/atom/Typography.tsx
src/components/common/molecule/WithdrawalModal.tsx
src/components/common/organism/Header.tsx
src/components/wrapper/ListItemContainer.tsx
src/hooks/api/home/notice/useGetPeerReviewNotification.tsx
src/hooks/common/useHistory.tsx
src/pages/developer/DeveloperPage.tsx
src/pages/notification/index/molecule/NotificationType.tsx
src/pages/notification/index/molecule/ProjectType.tsx
src/pages/peer/detail/atom/PeerProfileCard.tsx
src/pages/peer/detail/organism/PeerCardContent.tsx
src/pages/project/index/organism/MyProject.tsx
src/pages/project/join/template/ProjectJoinPage.tsx

- [] Issue 
<br>
<br><br>
<br><br>
<br><br>
- Close #
<br><br>

GA 스크립트 추가, 알림 컴포넌트 줄바꿈 추가 

---

src/constants/images.ts
src/pages/home/index/molecule/UserProfileList.tsx
src/pages/home/index/template/HomePage.tsx
src/pages/peer/project/template/MyProjectListPage.tsx

<br>
- 홈 이미지 수정 및 불필요한 코드 삭제
<br><br>

refactor: 홈 이미지 수정 및 불필요한 코드 삭제

---

index.html

<br>
<br><br>
<br><br>
<br><br>
- Close #
<br><br>

refac: gtm 스크립트 위치 변경

---

src/hooks/api/member/index/useGetMypageInfo.tsx
src/hooks/store/useReviewState.tsx

<br>
<br><br>
- 마이페이지 종합평가 이슈와 캐싱 문제를 해결합니다
<br><br>

fix: 마이페이지 오류 해결

---

src/components/common/atom/PeerCard.tsx

<br>
- 피어카드의 고정된 height값을 제거합니다
<br><br>

style: 피어카드 고정된 height값 삭제

---

src/components/common/molecule/ProfileListItem.tsx
src/pages/peer/detail/atom/PeerProfileCard.tsx

<br>
- 종합점수 14점 이상의 경우로 분기처리
<br><br>

refactor: 종합점수 14점 이상의 경우로 분기처리
